spring.application.name=JournalApplication
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
#spring.data.mongodb.username= myusername
#spring.data.mongodb.username= mypassword
spring.data.mongodb.database=journalDB